flowchart LR
http://data.europa.eu/bna/asd487ae75[High-value dataset categories]
click http://data.europa.eu/bna/asd487ae75 href "http://data.europa.eu/bna/asd487ae75"
http://data.europa.eu/bna/asd487ae75-->http://data.europa.eu/bna/c_164e0bf5
http://data.europa.eu/bna/c_164e0bf5["Meteorologie"]
click http://data.europa.eu/bna/c_164e0bf5 href "http://data.europa.eu/bna/c_164e0bf5"
http://data.europa.eu/bna/c_164e0bf5-->http://data.europa.eu/bna/c_13e3cf16
http://data.europa.eu/bna/c_13e3cf16["NWP-Modelldaten"]
click http://data.europa.eu/bna/c_13e3cf16 href "http://data.europa.eu/bna/c_13e3cf16"
http://data.europa.eu/bna/c_164e0bf5-->http://data.europa.eu/bna/c_36807466
http://data.europa.eu/bna/c_36807466["Klimadaten: validierte Beobachtungen"]
click http://data.europa.eu/bna/c_36807466 href "http://data.europa.eu/bna/c_36807466"
http://data.europa.eu/bna/c_164e0bf5-->http://data.europa.eu/bna/c_3af3368c
http://data.europa.eu/bna/c_3af3368c["Beobachtungsmessdaten von Wetterstationen"]
click http://data.europa.eu/bna/c_3af3368c href "http://data.europa.eu/bna/c_3af3368c"
http://data.europa.eu/bna/c_164e0bf5-->http://data.europa.eu/bna/c_be47b010
http://data.europa.eu/bna/c_be47b010["Wetterwarnungen"]
click http://data.europa.eu/bna/c_be47b010 href "http://data.europa.eu/bna/c_be47b010"
http://data.europa.eu/bna/c_164e0bf5-->http://data.europa.eu/bna/c_d13a4420
http://data.europa.eu/bna/c_d13a4420["Radardaten"]
click http://data.europa.eu/bna/c_d13a4420 href "http://data.europa.eu/bna/c_d13a4420"
http://data.europa.eu/bna/asd487ae75-->http://data.europa.eu/bna/c_a9135398
http://data.europa.eu/bna/c_a9135398["Unternehmen und Eigentümerschaft von Unternehmen"]
click http://data.europa.eu/bna/c_a9135398 href "http://data.europa.eu/bna/c_a9135398"
http://data.europa.eu/bna/c_a9135398-->http://data.europa.eu/bna/c_56a1bf47
http://data.europa.eu/bna/c_56a1bf47["Grundlegende Angaben zum Unternehmen: Schlüsselattribute"]
click http://data.europa.eu/bna/c_56a1bf47 href "http://data.europa.eu/bna/c_56a1bf47"
http://data.europa.eu/bna/c_a9135398-->http://data.europa.eu/bna/c_8f0fac04
http://data.europa.eu/bna/c_8f0fac04["Unternehmensunterlagen und -abschlüsse"]
click http://data.europa.eu/bna/c_8f0fac04 href "http://data.europa.eu/bna/c_8f0fac04"
http://data.europa.eu/bna/asd487ae75-->http://data.europa.eu/bna/c_ac64a52d
http://data.europa.eu/bna/c_ac64a52d["Georaum"]
click http://data.europa.eu/bna/c_ac64a52d href "http://data.europa.eu/bna/c_ac64a52d"
http://data.europa.eu/bna/c_ac64a52d-->http://data.europa.eu/bna/c_60182062
http://data.europa.eu/bna/c_60182062["Gebäude"]
click http://data.europa.eu/bna/c_60182062 href "http://data.europa.eu/bna/c_60182062"
http://data.europa.eu/bna/c_ac64a52d-->http://data.europa.eu/bna/c_642643e6
http://data.europa.eu/bna/c_642643e6["Landwirtschaftliche Parzellen"]
click http://data.europa.eu/bna/c_642643e6 href "http://data.europa.eu/bna/c_642643e6"
http://data.europa.eu/bna/c_ac64a52d-->http://data.europa.eu/bna/c_6a3f6896
http://data.europa.eu/bna/c_6a3f6896["Flurstücke/Grundstücke (Katasterparzellen)"]
click http://data.europa.eu/bna/c_6a3f6896 href "http://data.europa.eu/bna/c_6a3f6896"
http://data.europa.eu/bna/c_ac64a52d-->http://data.europa.eu/bna/c_6c2bb82d
http://data.europa.eu/bna/c_6c2bb82d["Geografische Bezeichnungen"]
click http://data.europa.eu/bna/c_6c2bb82d href "http://data.europa.eu/bna/c_6c2bb82d"
http://data.europa.eu/bna/c_ac64a52d-->http://data.europa.eu/bna/c_9427236f
http://data.europa.eu/bna/c_9427236f["Verwaltungseinheiten"]
click http://data.europa.eu/bna/c_9427236f href "http://data.europa.eu/bna/c_9427236f"
http://data.europa.eu/bna/c_ac64a52d-->http://data.europa.eu/bna/c_c3de25e4
http://data.europa.eu/bna/c_c3de25e4["Adressen"]
click http://data.europa.eu/bna/c_c3de25e4 href "http://data.europa.eu/bna/c_c3de25e4"
http://data.europa.eu/bna/c_ac64a52d-->http://data.europa.eu/bna/c_fbd2fc3f
http://data.europa.eu/bna/c_fbd2fc3f["Referenzparzellen"]
click http://data.europa.eu/bna/c_fbd2fc3f href "http://data.europa.eu/bna/c_fbd2fc3f"
http://data.europa.eu/bna/asd487ae75-->http://data.europa.eu/bna/c_b79e35eb
http://data.europa.eu/bna/c_b79e35eb["Mobilität"]
click http://data.europa.eu/bna/c_b79e35eb href "http://data.europa.eu/bna/c_b79e35eb"
http://data.europa.eu/bna/c_b79e35eb-->http://data.europa.eu/bna/c_4b74ea13
http://data.europa.eu/bna/c_4b74ea13["Verkehrsnetze"]
click http://data.europa.eu/bna/c_4b74ea13 href "http://data.europa.eu/bna/c_4b74ea13"
http://data.europa.eu/bna/c_b79e35eb-->http://data.europa.eu/bna/c_b151a0ba
http://data.europa.eu/bna/c_b151a0ba["Binnenschifffahrtsdatensätze"]
click http://data.europa.eu/bna/c_b151a0ba href "http://data.europa.eu/bna/c_b151a0ba"
http://data.europa.eu/bna/asd487ae75-->http://data.europa.eu/bna/c_dd313021
http://data.europa.eu/bna/c_dd313021["Erdbeobachtung und Umwelt"]
click http://data.europa.eu/bna/c_dd313021 href "http://data.europa.eu/bna/c_dd313021"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_06b1eec4
http://data.europa.eu/bna/c_06b1eec4["Gewässernetz"]
click http://data.europa.eu/bna/c_06b1eec4 href "http://data.europa.eu/bna/c_06b1eec4"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_315692ad
http://data.europa.eu/bna/c_315692ad["Höhe"]
click http://data.europa.eu/bna/c_315692ad href "http://data.europa.eu/bna/c_315692ad"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_38933a65
http://data.europa.eu/bna/c_38933a65["Abfall"]
click http://data.europa.eu/bna/c_38933a65 href "http://data.europa.eu/bna/c_38933a65"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_43f88346
http://data.europa.eu/bna/c_43f88346["Wasser"]
click http://data.europa.eu/bna/c_43f88346 href "http://data.europa.eu/bna/c_43f88346"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_4ba9548e
http://data.europa.eu/bna/c_4ba9548e["Emissionen"]
click http://data.europa.eu/bna/c_4ba9548e href "http://data.europa.eu/bna/c_4ba9548e"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_4d63300b
http://data.europa.eu/bna/c_4d63300b["Horizontale Rechtsvorschriften"]
click http://data.europa.eu/bna/c_4d63300b href "http://data.europa.eu/bna/c_4d63300b"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_4dd389c5
http://data.europa.eu/bna/c_4dd389c5["Mineralische Bodenschätze"]
click http://data.europa.eu/bna/c_4dd389c5 href "http://data.europa.eu/bna/c_4dd389c5"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_59c93ba5
http://data.europa.eu/bna/c_59c93ba5["Produktions- und Industrieanlagen"]
click http://data.europa.eu/bna/c_59c93ba5 href "http://data.europa.eu/bna/c_59c93ba5"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_59e64dd4
http://data.europa.eu/bna/c_59e64dd4["Klima"]
click http://data.europa.eu/bna/c_59e64dd4 href "http://data.europa.eu/bna/c_59e64dd4"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_63b37dd4
http://data.europa.eu/bna/c_63b37dd4["Luft"]
click http://data.europa.eu/bna/c_63b37dd4 href "http://data.europa.eu/bna/c_63b37dd4"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_63be22bd
http://data.europa.eu/bna/c_63be22bd["Gebiete mit naturbedingten Risiken"]
click http://data.europa.eu/bna/c_63be22bd href "http://data.europa.eu/bna/c_63be22bd"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_793164b6
http://data.europa.eu/bna/c_793164b6["Verteilung der Arten"]
click http://data.europa.eu/bna/c_793164b6 href "http://data.europa.eu/bna/c_793164b6"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_7b8fbb64
http://data.europa.eu/bna/c_7b8fbb64["Umweltüberwachungseinrichtungen"]
click http://data.europa.eu/bna/c_7b8fbb64 href "http://data.europa.eu/bna/c_7b8fbb64"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_83aa10a6
http://data.europa.eu/bna/c_83aa10a6["Schutzgebiete"]
click http://data.europa.eu/bna/c_83aa10a6 href "http://data.europa.eu/bna/c_83aa10a6"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_87a129d9
http://data.europa.eu/bna/c_87a129d9["Boden"]
click http://data.europa.eu/bna/c_87a129d9 href "http://data.europa.eu/bna/c_87a129d9"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_91185a85
http://data.europa.eu/bna/c_91185a85["Orthofotografie"]
click http://data.europa.eu/bna/c_91185a85 href "http://data.europa.eu/bna/c_91185a85"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_ad9ae929
http://data.europa.eu/bna/c_ad9ae929["Bodennutzung"]
click http://data.europa.eu/bna/c_ad9ae929 href "http://data.europa.eu/bna/c_ad9ae929"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_af646f5b
http://data.europa.eu/bna/c_af646f5b["Bewirtschaftungsgebiete/Schutzgebiete/geregelte Gebiete und Berichterstattungseinheiten"]
click http://data.europa.eu/bna/c_af646f5b href "http://data.europa.eu/bna/c_af646f5b"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_b21e1296
http://data.europa.eu/bna/c_b21e1296["Bodenbedeckung"]
click http://data.europa.eu/bna/c_b21e1296 href "http://data.europa.eu/bna/c_b21e1296"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_b40e6d46
http://data.europa.eu/bna/c_b40e6d46["Ozeanografisch-geografische Kennwerte"]
click http://data.europa.eu/bna/c_b40e6d46 href "http://data.europa.eu/bna/c_b40e6d46"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_b7de66cd
http://data.europa.eu/bna/c_b7de66cd["Energiequellen"]
click http://data.europa.eu/bna/c_b7de66cd href "http://data.europa.eu/bna/c_b7de66cd"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_b7f6a4f3
http://data.europa.eu/bna/c_b7f6a4f3["Erhaltung der Natur und der biologischen Vielfalt"]
click http://data.europa.eu/bna/c_b7f6a4f3 href "http://data.europa.eu/bna/c_b7f6a4f3"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_c3919aec
http://data.europa.eu/bna/c_c3919aec["Lebensräume und Biotope"]
click http://data.europa.eu/bna/c_c3919aec href "http://data.europa.eu/bna/c_c3919aec"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_c873f344
http://data.europa.eu/bna/c_c873f344["Biogeografische Regionen"]
click http://data.europa.eu/bna/c_c873f344 href "http://data.europa.eu/bna/c_c873f344"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_e3f55603
http://data.europa.eu/bna/c_e3f55603["Geologie"]
click http://data.europa.eu/bna/c_e3f55603 href "http://data.europa.eu/bna/c_e3f55603"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_e4358335
http://data.europa.eu/bna/c_e4358335["Lärm"]
click http://data.europa.eu/bna/c_e4358335 href "http://data.europa.eu/bna/c_e4358335"
http://data.europa.eu/bna/c_dd313021-->http://data.europa.eu/bna/c_f399050e
http://data.europa.eu/bna/c_f399050e["Meeresregionen"]
click http://data.europa.eu/bna/c_f399050e href "http://data.europa.eu/bna/c_f399050e"
http://data.europa.eu/bna/asd487ae75-->http://data.europa.eu/bna/c_e1da4e07
http://data.europa.eu/bna/c_e1da4e07["Statistik"]
click http://data.europa.eu/bna/c_e1da4e07 href "http://data.europa.eu/bna/c_e1da4e07"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_04bf94a3
http://data.europa.eu/bna/c_04bf94a3["Armut"]
click http://data.europa.eu/bna/c_04bf94a3 href "http://data.europa.eu/bna/c_04bf94a3"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_20cd11bb
http://data.europa.eu/bna/c_20cd11bb["Statistik des internationalen Warenverkehrs der EU – Ausfuhren und Einfuhren Aufschlüsselung gleichzeitig nach Partnern, Produkten und Warenströmen"]
click http://data.europa.eu/bna/c_20cd11bb href "http://data.europa.eu/bna/c_20cd11bb"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_23385471
http://data.europa.eu/bna/c_23385471["Potenzielle Arbeitskräfte"]
click http://data.europa.eu/bna/c_23385471 href "http://data.europa.eu/bna/c_23385471"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_2aed31f9
http://data.europa.eu/bna/c_2aed31f9["Industrieller Erzeugerpreisindex – Aufschlüsselung nach Tätigkeit"]
click http://data.europa.eu/bna/c_2aed31f9 href "http://data.europa.eu/bna/c_2aed31f9"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_317b9493
http://data.europa.eu/bna/c_317b9493["Bevölkerung, Fertilität, Mortalität"]
click http://data.europa.eu/bna/c_317b9493 href "http://data.europa.eu/bna/c_317b9493"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_34abf8c1
http://data.europa.eu/bna/c_34abf8c1["Industrieproduktion"]
click http://data.europa.eu/bna/c_34abf8c1 href "http://data.europa.eu/bna/c_34abf8c1"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_424bb0b4
http://data.europa.eu/bna/c_424bb0b4["Laufende Gesundheitsausgaben"]
click http://data.europa.eu/bna/c_424bb0b4 href "http://data.europa.eu/bna/c_424bb0b4"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_4ac557e7
http://data.europa.eu/bna/c_4ac557e7["Ausgaben und Einnahmen des Staates"]
click http://data.europa.eu/bna/c_4ac557e7 href "http://data.europa.eu/bna/c_4ac557e7"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_4acb6bf3
http://data.europa.eu/bna/c_4acb6bf3["Mortalität"]
click http://data.europa.eu/bna/c_4acb6bf3 href "http://data.europa.eu/bna/c_4acb6bf3"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_59627af3
http://data.europa.eu/bna/c_59627af3["Volkswirtschaftliche Gesamtrechnungen – Schlüsselindikatoren für private Haushalte"]
click http://data.europa.eu/bna/c_59627af3 href "http://data.europa.eu/bna/c_59627af3"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_6a7250c1
http://data.europa.eu/bna/c_6a7250c1["Fertilität"]
click http://data.europa.eu/bna/c_6a7250c1 href "http://data.europa.eu/bna/c_6a7250c1"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_92874eb2
http://data.europa.eu/bna/c_92874eb2["Umweltgesamtrechnungen und -statistiken"]
click http://data.europa.eu/bna/c_92874eb2 href "http://data.europa.eu/bna/c_92874eb2"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_95da87c7
http://data.europa.eu/bna/c_95da87c7["Volkswirtschaftliche Gesamtrechnungen – Schlüsselindikatoren für Kapitalgesellschaften"]
click http://data.europa.eu/bna/c_95da87c7 href "http://data.europa.eu/bna/c_95da87c7"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_a2c6dcd8
http://data.europa.eu/bna/c_a2c6dcd8["Erwerbstätigkeit"]
click http://data.europa.eu/bna/c_a2c6dcd8 href "http://data.europa.eu/bna/c_a2c6dcd8"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_a3767648
http://data.europa.eu/bna/c_a3767648["Tourismusströme in Europa"]
click http://data.europa.eu/bna/c_a3767648 href "http://data.europa.eu/bna/c_a3767648"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_a49ec591
http://data.europa.eu/bna/c_a49ec591["Verkaufsmengen nach Tätigkeit"]
click http://data.europa.eu/bna/c_a49ec591 href "http://data.europa.eu/bna/c_a49ec591"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_a8b937c4
http://data.europa.eu/bna/c_a8b937c4["Ungleichheit"]
click http://data.europa.eu/bna/c_a8b937c4 href "http://data.europa.eu/bna/c_a8b937c4"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_b72b721f
http://data.europa.eu/bna/c_b72b721f["Volkswirtschaftliche Gesamtrechnungen – BIP-Hauptaggregate"]
click http://data.europa.eu/bna/c_b72b721f href "http://data.europa.eu/bna/c_b72b721f"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_c0022235
http://data.europa.eu/bna/c_c0022235["Harmonisierte Verbraucherpreisindizes"]
click http://data.europa.eu/bna/c_c0022235 href "http://data.europa.eu/bna/c_c0022235"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_dd8f4797
http://data.europa.eu/bna/c_dd8f4797["Konsolidierte Bruttoverschuldung des Staates"]
click http://data.europa.eu/bna/c_dd8f4797 href "http://data.europa.eu/bna/c_dd8f4797"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_f2b50efd
http://data.europa.eu/bna/c_f2b50efd["Bevölkerung"]
click http://data.europa.eu/bna/c_f2b50efd href "http://data.europa.eu/bna/c_f2b50efd"
http://data.europa.eu/bna/c_e1da4e07-->http://data.europa.eu/bna/c_fd4e881c
http://data.europa.eu/bna/c_fd4e881c["Erwerbslosigkeit"]
click http://data.europa.eu/bna/c_fd4e881c href "http://data.europa.eu/bna/c_fd4e881c"
